# Generated by Django 3.0.2 on 2020-04-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Label',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
