# Generated by Django 3.0.2 on 2020-04-01 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20200401_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter_name', models.CharField(max_length=20)),
                ('comment_body', models.CharField(max_length=1000)),
                ('comment_time', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blogapp.Post')),
            ],
        ),
    ]
