# Generated by Django 3.0.2 on 2020-04-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20200418_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Default'), ('Publish', 'Publish')], default='Draft', max_length=20),
        ),
    ]
