# Generated by Django 3.0.2 on 2020-04-02 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=200)),
                ('post_label', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blogapp.Post')),
            ],
        ),
    ]
