# Generated by Django 3.0.2 on 2020-04-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_auto_20200418_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(blank=True, default='Write here'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Draft', 'Default'), ('Publish', 'Publish')], default=('Publish', 'Publish'), max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, default='titile', max_length=250),
        ),
    ]
