# Generated by Django 3.0.2 on 2020-04-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_auto_20200418_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Default'), ('Publish', 'Publish')], default='Draft', max_length=20),
        ),
    ]
