# Generated by Django 3.0.2 on 2020-04-02 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_auto_20200402_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Label',
        ),
    ]
