# Generated by Django 3.0.2 on 2020-04-05 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_auto_20200405_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Post', related_query_name='Post', to='blogapp.Comment'),
        ),
    ]
