# Generated by Django 3.0.2 on 2020-04-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_auto_20200418_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(blank=True, choices=[('Default', 'Draft'), ('Publish', 'Publish')], default='Default', max_length=20),
        ),
    ]
