# Generated by Django 3.0.2 on 2020-04-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_auto_20200418_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('', 'Draft'), ('Publish', 'Publish')], default='', max_length=20),
        ),
    ]
