# Generated by Django 3.0.2 on 2020-04-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_auto_20200418_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Draft', ''), ('Publish', 'Publish')], default='Draft', max_length=20),
        ),
    ]
