# Generated by Django 3.0.2 on 2020-04-08 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_auto_20200405_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Post', related_query_name='Poster', to='blogapp.Post'),
        ),
    ]
