# Generated by Django 3.0.2 on 2020-04-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0014_auto_20200418_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Draft', 'Default'), ('Publish', 'Publish')], default='Draft', max_length=20),
        ),
    ]
