# Generated by Django 3.0.2 on 2020-04-09 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0015_auto_20200408_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog', related_query_name='blogging', to='blogapp.Post'),
        ),
    ]
